name: Node.js Setup
description: 'Setup Node.js, install dependencies, build, and package the application'

runs:
  using: 'composite'

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Lint
      run: npm run lint
      shell: bash

    - name: Format
      run: npm run format
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Package
      run: npm run package
      shell: bash
