name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: "削除対象のインフラを管理するディレクトリを選択してください"
        required: true
        type: string
        default: "app-infras/environment/hello-world"

env:
  TERRAFORM_VERSION: "1.9.7"

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-configure

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init -backend-config=./backend_config.hcl
        working-directory: ${{ github.event.inputs.working-directory }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ github.event.inputs.working-directory }}
